#format build args
# 'gcr.io/PROJECT ID/ DESIRED IMAGE NAME OR IMAGE ALREADY EXISTING : DESIRED TAG (USE $SHORT_SHA base tag on sha id)'

#format push args
# 'gcr.io/PROJECT ID/ IMAGE NAME SAME AS ABOVE : DESIRED TAG (USE $SHORT_SHA base tag on short sha id)'

#name and args for deploy:
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args:
  #     [
  #       'run',
  #       'deploy',
  #       'IMAGE REP0 NAME',
  #       '--image=gcr.io/PROJECT ID/IMAGE REPO NAME:$SHORT_SHA',
  #       '--region=us-central1', (this could be something different must match projec host name)
  #     ]


steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'us-central1-docker.pkg.dev/${PROJECT_ID}/sewerfish-artifact-1/echo23:$SHORT_SHA',
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'us-central1-docker.pkg.dev/${PROJECT_ID}/sewerfish-artifact-1/echo23:$SHORT_SHA']


   # Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'echo23-2023-02-08-a'
      - '--image'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/sewerfish-artifact-1/echo23:$SHORT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'