# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', 't', 'gcr.io/final-solution-379503/sewerfish:$_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/final-solution-379503/gcr.io/final-solution-379503/sewerfish:$_SHA']